In [1]:
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
categories = {
    "Sports" : "football basketball match player goal",
    "Technology" : "computer software AI technology smartphone",
    "Food" : "restaurant cooking food recipe delicious"
}

In [3]:
new_article = "AI technology software computer"

In [4]:
texts = list(categories.values()) + [new_article]

In [5]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(texts)
print(X.toarray())

[[0 1 0 0 0 0 1 1 1 1 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0 0 0 1 1 1]
 [0 0 0 1 1 1 0 0 0 0 1 1 0 0 0]
 [1 0 1 0 0 0 0 0 0 0 0 0 0 1 1]]

In [6]:
print(vectorizer.get_feature_names_out())

['ai' 'basketball' 'computer' 'cooking' 'delicious' 'food' 'football'
 'goal' 'match' 'player' 'recipe' 'restaurant' 'smartphone' 'software'
 'technology']

In [7]:
import pandas as pd
df = pd.DataFrame(
    X.toarray(), columns=vectorizer.get_feature_names_out()
)
df

,ai,basketball,computer,cooking,delicious,food,football,goal,match,player,recipe,restaurant,smartphone,software,technology
0,0,1,0,0,0,0,1,1,1,1,0,0,0,0,0
1,1,0,1,0,0,0,0,0,0,0,0,0,1,1,1
2,0,0,0,1,1,1,0,0,0,0,1,1,0,0,0
3,1,0,1,0,0,0,0,0,0,0,0,0,0,1,1

In [8]:
new_vector = vectorizer.transform([new_article])

In [9]:
df = pd.DataFrame(
    new_vector.toarray(), columns=vectorizer.get_feature_names_out(),
)
df

,ai,basketball,computer,cooking,delicious,food,football,goal,match,player,recipe,restaurant,smartphone,software,technology
0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,1

In [10]:
new_vector = X[-1]
scores = {}

for i, category in enumerate(categories):
    category_vector = X[i]

    matches = ((category_vector > 0).multiply(new_vector > 0)).sum()
    scores[category] = matches

for category, score in scores.items():
    print(f"{category}: {score}")

predicted_category = max(scores, key=scores.get)
print(f"Predicted Category: {predicted_category}")

Sports: 0
Technology: 4
Food: 0
Predicted Category: Technology