In [12]:
#!pip uninstall -y transformers
#!pip install transformers==4.57.0

### Text Classification

In [13]:
import transformers
print(transformers.__version__)

4.57.0

In [14]:
import pandas as pd
from transformers import pipeline

In [25]:
classifier = pipeline('text-classification',model='distilbert/distilbert-base-uncased-finetuned-sst-2-english')

result = classifier("I love this university!")

print(result)

Device set to use cpu

[{'label': 'POSITIVE', 'score': 0.9998780488967896}]

In [22]:
classifier1 = pipeline("sentiment-analysis")

result = classifier1("I love this university!")

print(result)

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cpu

[{'label': 'POSITIVE', 'score': 0.9998780488967896}]

In [27]:
text = 'It was horrible. It ruined our whole day'
result = classifier(text)
df = pd.DataFrame(result)

In [28]:
df

      label     score
0  NEGATIVE  0.999807

### Question - Answering

In [29]:
qa = pipeline('question-answering')

No model was supplied, defaulted to distilbert/distilbert-base-cased-distilled-squad and revision 564e9b5 (https://huggingface.co/distilbert/distilbert-base-cased-distilled-squad).
Using a pipeline without specifying a model name and revision in production is not recommended.
C:\Users\UserG\Desktop\NLP\.venv1\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\UserG\.cache\huggingface\hub\models--distilbert--distilbert-base-cased-distilled-squad. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Device set to use cpu

In [32]:
text = '''The tiger (Panthera tigris) is a large cat and a member of the genus Panthera native to Asia. It has a powerful, muscular body with a large head and paws, a long tail and orange fur with black, mostly vertical stripes. It is traditionally classified into nine recent subspecies, though some recognise only two subspecies, mainland Asian tigers and the island tigers of the Sunda Islands.

Throughout the tiger's range, it inhabits mainly forests, from coniferous and temperate broadleaf and mixed forests in the Russian Far East and Northeast China to tropical and subtropical moist broadleaf forests on the Indian subcontinent and Southeast Asia. The tiger is an apex predator and preys mainly on ungulates, which it takes by ambush. It lives a mostly solitary life and occupies home ranges, defending these from individuals of the same sex. The range of a male tiger overlaps with that of multiple females with whom he mates. Females give birth to usually two or three cubs that stay with their mother for about two years. When becoming independent, they leave their mother's home range and establish their own.

Since the early 20th century, tiger populations have lost at least 93% of their historic range and are locally extinct in West and Central Asia, in large areas of China and on the islands of Java and Bali. Today, the tiger's range is severely fragmented. It is listed as Endangered on the IUCN Red List of Threatened Species, as its range is thought to have declined by 53% to 68% since the late 1990s. Major threats to tigers are habitat destruction and fragmentation due to deforestation, poaching for fur and the illegal trade of body parts for medicinal purposes. Tigers are also victims of human–wildlife conflict as they attack and prey on livestock in areas where natural prey is scarce. The tiger is legally protected in all range countries. National conservation measures consist of action plans, anti-poaching patrols and schemes for monitoring tiger populations. In several range countries, wildlife corridors have been established and tiger reintroduction is planned.

The tiger is among the most popular of the world's charismatic megafauna. It has been kept in captivity since ancient times and has been trained to perform in circuses and other entertainment shows. The tiger featured prominently in the ancient mythology and folklore of cultures throughout its historic range and has continued to appear in culture worldwide.'''

In [44]:
#question = 'Where is the tiger found?'
question = 'What is Panthera tigris?'
#question = 'What is the fur color of a tiger?'

In [45]:
a = qa (question = question,context=text)
a

{'score': 0.17163394391536713, 'start': 31, 'end': 42, 'answer': 'a large cat'}

In [47]:
ner  = pipeline('ner',model='dslim/bert-base-NER')

C:\Users\UserG\Desktop\NLP\.venv1\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\UserG\.cache\huggingface\hub\models--dslim--bert-base-NER. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Some weights of the model checkpoint at dslim/bert-base-NER were not used when initializing BertForTokenClassification: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Device set to use cpu

In [48]:
result = ner(text)
df = pd.DataFrame(result)

In [49]:
df

    entity     score  index         word  start   end
0   B-MISC  0.627010      4      Panther     11    18
1   B-MISC  0.656083     20      Panther     69    76
2   I-MISC  0.504560     21          ##a     76    77
3    B-LOC  0.999729     24         Asia     88    92
4   B-MISC  0.999399     71        Asian    331   336
5    B-LOC  0.998980     81          Sun    373   376
6    I-LOC  0.988173     82         ##da    376   378
7    I-LOC  0.998739     83      Islands    379   386
8    B-LOC  0.985585    110      Russian    512   519
9    I-LOC  0.994686    111          Far    520   523
10   I-LOC  0.998679    112         East    524   528
11   B-LOC  0.997788    114    Northeast    533   542
12   I-LOC  0.997221    115        China    543   548
13  B-MISC  0.995052    126       Indian    608   614
14   I-LOC  0.856976    128  ##continent    618   627
15   B-LOC  0.998841    130    Southeast    632   641
16   I-LOC  0.998457    131         Asia    642   646
17   B-LOC  0.997118    252         West   1237  1241
18   B-LOC  0.997253    254      Central   1246  1253
19   I-LOC  0.998044    255         Asia   1254  1258
20   B-LOC  0.999775    261        China   1278  1283
21   B-LOC  0.999660    267         Java   1306  1310
22   B-LOC  0.999711    269         Bali   1315  1319
23   B-ORG  0.518072    292         IUCN   1404  1408
24  I-MISC  0.980068    293          Red   1409  1412
25  I-MISC  0.986894    294         List   1413  1417
26  I-MISC  0.995066    295           of   1418  1420
27  I-MISC  0.974597    296            T   1421  1422
28  I-MISC  0.991215    299       ##ened   1427  1431
29  I-MISC  0.992068    300      Species   1432  1439

In [ ]:
#
#
#

In [ ]:
df