In [1]:
# Import Library
# CountVectorizer automatically:	tokenizes text, creates vocabulary, counts words 

from sklearn.feature_extraction.text import CountVectorizer

In [2]:
# Create Sample Documents

documents = [
    "I love NLP",
    "I love AI",
    "NLP is interesting",
    "AI is powerful"
]

print(documents)

['I love NLP', 'I love AI', 'NLP is interesting', 'AI is powerful']

In [3]:
# Create Bag of Words Model
# fit_transform() does two things:   1.	Learns vocabulary   2.	Creates vectors 

vectorizer = CountVectorizer()

X = vectorizer.fit_transform(documents)

In [4]:
# Show Vocabulary
# Scikit-learn designed the default token_pattern requiring 2 or more characters so not include 'I'
print(vectorizer.get_feature_names_out())

['ai' 'interesting' 'is' 'love' 'nlp' 'powerful']

In [5]:
# Display BoW Matrix
print(X.toarray())

[[0 0 0 1 1 0]
 [1 0 0 1 0 0]
 [0 1 1 0 1 0]
 [1 0 1 0 0 1]]

In [6]:
# Convert Matrix into DataFrame

import pandas as pd

bow_df = pd.DataFrame(
    X.toarray(),
    columns=vectorizer.get_feature_names_out()
)

bow_df

   ai  interesting  is  love  nlp  powerful
0   0            0   0     1    1         0
1   1            0   0     1    0         0
2   0            1   1     0    1         0
3   1            0   1     0    0         1

In [7]:
# Test a New Sentence
new_sentence = [
    "It is a pretty cat"
]

In [8]:
new_vector = vectorizer.transform(new_sentence)

print(new_vector.toarray())

[[0 0 1 0 0 0]]

In [9]:
import pandas as pd

bow_df = pd.DataFrame(
    new_vector.toarray(),
    columns=vectorizer.get_feature_names_out()
)

bow_df

   ai  interesting  is  love  nlp  powerful
0   0            0   1     0    0         0